"""An implementation of the model from:

Mathematical modeling and sensitivity analysis of G1/S phase in the cell cycle
including the DNA-damage signal transduction pathway.  Kazunari Iwamoto, 
Yoshihiko Tashima, Hiroyuki Hamada, Yukihiro Eguchi, Masahiro Okamoto. 
BioSystems. 2008 May 23;94(2008):109-117.
doi:10.1016/j.biosystems.2008.05.016

http://www.sciencedirect.com/science/article/pii/S0303264708001330

Implemented by: David Fan

IMPORTANT: Some ODEs generated by this model need to be overridden. These 
are located in "run_fan_model.py". "_source" needs to be set to the variable
corresponding to the species "__source()"
"""

from pysb import *
from pysb.util import *
from pysb.macros import *
from pysb.bng import *
from pysb.integrate import odesolve
import pylab as pl
from numpy import linspace
from sympy import sympify

Model()

def set_dna_damage(damage):
	model.parameters['DDS_0'].value = damage
	#Parameter("DDS", damage)
	
	# "Make all model components visible as symbols in the caller's global namespace"
	#alias_model_components()

def declare_monomers():
	"""Declare the monomers in the Iwamoto model
	'Y' is the phosphorylation state
	'b' is the binding site between p## and CDKs
	'c' is the binding site between cyclins and CDKs
	'i' is the binding site for inhibitors"""
	
	Monomer("Signal")
	Monomer("SignalDamp")
	# **Cyclins**
	Monomer("CycD", [        'c'])
	Monomer("CycE", [        'c'])
	Monomer("CycA", [        'c'])
	
	# **Cyclin-dependent kinases**
	Monomer("CDK46",['Y','b','c'], {'Y':['u','p']})
	Monomer("CDK2",	['Y','b','c'], {'Y':['u','p']})
	
	# **Regulatory proteins**
	Monomer("p27", 	[    'b'])
	Monomer("p21", 	[    'b'])
	Monomer("p16", 	[    'b'])
	Monomer("p53",	[    'b'])
	Monomer("Rb", 	['Y','b'], {'Y':['u','pp','pppp']})
	Monomer("E2F", 	[    'b'])
	Monomer("Mdm2",	['i'])
	Monomer("X")
	Monomer("I")
	
# 	alias_model_components()

def declare_parameters():
	Parameter("Y0_0", 3.00e-2)	# 	CycD
	Parameter("Y1_0", 1.00e-3)	# 	CycE
	Parameter("Y2_0", 4.00e-5)	# 	CycA
	Parameter("Y3_0", 5.00e+00)	# 	CDK4/6
	Parameter("Y4_0", 1.35e+01)	# 	CDK2
	Parameter("Y5_0", 2.00e+00)	# 	CycD/CDK4/6
	Parameter("Y6_0", 1.00e-03)	# 	CycE/CDK2
	Parameter("Y7_0", 1.00e-03)	# 	CycE/CDK2-P
	Parameter("Y8_0", 4.00e-04)	# 	CycA/CDK2
	Parameter("Y9_0", 1.00e-04)	# 	CycA/CDK2-P
	Parameter("Y10_0", 1.00e+01)	# 	p27
	Parameter("Y11_0", 1.00e-03)	# 	p27/CycD/CDK4/6 (-P)
	Parameter("Y12_0", 1.00e+00)	# 	p27/CycE/CDK2 (-P)
	Parameter("Y13_0", 1.00e-04)	# 	p27/CycA/CDK2 (-P)
	Parameter("Y14_0", 0.00e+00)	# 	p21
	Parameter("Y15_0", 0.00e+00)	# 	p21/CycD/CDK4/6 (-P)
	Parameter("Y16_0", 0.00e+00)	# 	p21/CycE/CDK2 (-P)
	Parameter("Y17_0", 0.00e+00)	# 	p21/CycA/CDK2 (-P)
	Parameter("Y18_0", 1.00e-03)	# 	p16
	Parameter("Y19_0", 1.95e+00)	# 	Rb/E2F
	Parameter("Y20_0", 1.00e-03)	# 	Rb-PP/E2F
	Parameter("Y21_0", 0.00e+00)	# 	E2F
	Parameter("Y22_0", 1.00e-02)	# 	Rb-PPPP
	Parameter("Y23_0", 5.00e-02)	# 	Rb
	Parameter("Y24_0", 2.65e-02)	# 	p53
	Parameter("Y25_0", 2.35e-04)	# 	Mdm2
	Parameter("Y26_0", 1.00e-04)	# 	X
	Parameter("Y27_0", 0.00e+00)	# 	I
	Parameter("DDS_0")				# 	DDS
	
	##### Table A.2 #####
	# Kinetic parameters of proposed model
	Parameter("k1", 5.00e-03)	#
	Parameter("k2", 5.00e-04)	#
	Parameter("k3", 5.00e-03)	# !!!!! k4 and k3 have been interchanged in the ODEs. This follows figure 1
	Parameter("k4", 2.50e-03)	# !!!!! k4 and k3 have been interchanged in the ODEs. This follows figure 1
	Parameter("k5", 7.50e-02)	# 
	Parameter("k6", 2.50e-03)	#
	Parameter("k7", 1.25e-03)	#
	Parameter("k8", 2.50e-04)	#
	Parameter("k9", 8.00e-04)	#
	Parameter("k10", 5.00e-04)	#
	Parameter("k11", 1.00e-03)	#
	Parameter("k12", 2.00e-04)	#
	Parameter("k13", 5.00e-04)	#
	Parameter("k14", 5.00e-04)	#
	Parameter("k15", 5.00e-04)	#
	Parameter("k16", 5.00e-04)	#
	Parameter("k17", 2.00e-03)	#
	Parameter("k18", 5.00e-04)	#
	Parameter("k19", 5.00e-03)	#
	Parameter("k20", 5.00e-04)	#
	Parameter("k21", 5.00e-05)	#
	Parameter("k22", 2.50e-02)	#
	Parameter("k23", 1.75e-03)	#
	Parameter("k24", 2.25e-02)	# !!!!! k24 and k35 have been interchanged in the ODEs. This follows figure 1
	Parameter("k25", 1.75e-04)	#
	Parameter("k26", 2.25e-02)	#
	Parameter("k27", 1.75e-04)	#
	Parameter("k28", 1.90e-02)	#
	Parameter("k29", 5.00e-04)	#
	Parameter("k30", 2.50e-03)	# !!!!! k30 and k36 have been interchanged in the ODEs. This follows figure 1
	Parameter("k31", 1.75e-04)	#
	Parameter("k32", 2.50e-03)	#
	Parameter("k33", 1.75e-04)	#
	Parameter("k34", 5.00e-08)	#
	Parameter("k35", 1.00e-02)	# !!!!! k24 and k35 have been interchanged in the ODEs. This follows figure 1
	Parameter("k36", 1.50e-03)	# !!!!! k30 and k36 have been interchanged in the ODEs. This follows figure 1
	Parameter("k37", 5.00e-05)	#
	Parameter("k38", 1.00e-02)	#
	Parameter("k39", 5.00e-03)	#
	Parameter("k40", 2.00e-03)	#
	Parameter("k41", 5.00e-05)	#
	Parameter("k42", 1.00e-04)	#
	Parameter("k43", 5.00e-04)	#
	Parameter("k44", 5.00e-04)	#
	Parameter("k45", 5.00e-05)	#
	Parameter("k46", 2.50e-03)	#
	Parameter("k47", 2.50e-03)	#
	Parameter("k48", 2.50e-03)	#
	Parameter("k49", 4.00e-02)	#
	Parameter("k50", 2.50e-03)	#
	Parameter("k51", 5.00e-08)	#
	Parameter("k52", 5.00e-07)	#
	Parameter("k53", 5.00e-05)	#
	Parameter("k54", 1.00e-02)	#
	Parameter("k55", 5.00e-08)	#
	Parameter("k56", 5.00e-05)	#
	Parameter("k57", 5.00e-03)	#
	Parameter("k58", 5.00e-05)	#
	Parameter("k59", 5.00e-04)	#
	Parameter("k60", 1.00e-04)	#
	Parameter("k61", 1.50e+00)	#
	Parameter("k62", 1.00e-03)	#
	Parameter("k63", 9.40e-04)	#
	Parameter("k64", 2.00e-02)	#
	Parameter("k65", 9.50e+00)	#
	Parameter("k66", 1.00e+01)	#
	Parameter("k67", 5.00e-03)	#
	Parameter("k68", 5.00e-02)	#
	Parameter("k69", 8.00e-04)	#
	Parameter("k70", 6.00e+00)	#
	Parameter("k71", 4.00e-03)	#
	Parameter("k72", 1.00e-08)	#
	Parameter("k73", 7.72e-01)	#
	Parameter("k74", 5.56e-02)	#
	Parameter("k75", 2.00e-02)	#
	Parameter("One", 1)			#
# 	Parameter("Zero", 0)		#
# 	Parameter("Fast", 1000)		#
# 	Parameter("Slow", 1e-9)		#
# 	alias_model_components()
	
def declare_initial_conditions():
	Initial(CycD(c=None), Y0_0)	#0
	Initial(CycE(c=None), Y1_0)	#1
	Initial(CycA(c=None), Y2_0)	#2
	Initial(CDK46(Y='u',b=None,c=None), Y3_0)	#3
	Initial(CDK2(Y='u',b=None,c=None), Y4_0)	#4
	Initial(CycD(c=1) % CDK46(Y='p',b=None,c=1), Y5_0)	#5
	Initial(CycE(c=1) % CDK2(Y='u',b=None,c=1), Y6_0)	#6
	Initial(CycE(c=1) % CDK2(Y='p',b=None,c=1), Y7_0)	#7
	Initial(CycA(c=1) % CDK2(Y='u',b=None,c=1), Y8_0)	#8
	Initial(CycA(c=1) % CDK2(Y='p',b=None,c=1), Y9_0)	#9
	Initial(p27(b=None), Y10_0)	#10
	Initial(CycD(c=2) % CDK46(Y='p',b=1,c=2) % p27(b=1), Y11_0)	#11
	Initial(CycE(c=2) % CDK2(Y='p',b=1,c=2) % p27(b=1), Y12_0)	#12
	Initial(CycA(c=2) % CDK2(Y='p',b=1,c=2) % p27(b=1), Y13_0)	#13
	Initial(p21(b=None), Y14_0)	#14
	Initial(CycD(c=2) % CDK46(Y='p',b=1,c=2) % p21(b=1), Y15_0)	#15
	Initial(CycE(c=2) % CDK2(Y='p',b=1,c=2) % p21(b=1), Y16_0)	#16
	Initial(CycA(c=2) % CDK2(Y='p',b=1,c=2) % p21(b=1), Y17_0)	#17
	Initial(p16(b=None), Y18_0)	#18
	Initial(Rb(b=1,Y='u') % E2F(b=1), Y19_0)	#19
	Initial(Rb(b=1,Y='pp') % E2F(b=1), Y20_0)	#20
	Initial(E2F(b=None), Y21_0)	#21
	Initial(Rb(b=None,Y='pppp'), Y22_0)	#22
	Initial(Rb(b=None,Y='u'), Y23_0)	#23
	Initial(p53(b=None), Y24_0)	#24
	Initial(Mdm2(i=None), Y25_0)	#25
	Initial(X(), Y26_0)	#26
	Initial(I(), Y27_0)	#27
	Initial(Signal(), DDS_0) #28
	Initial(SignalDamp(), DDS_0) #29

# def declare_kinetic_parameters():
# 	
# 	
# 	alias_model_components()

#################
## Observables ##
#################
# Figure 6 (CycE, CycA, p27, E2F with no DNA-damage)
def declare_observables():
	Observable("OBS_p27", p27(b=None))
	Observable("OBS_p53", p53(b=None))
	Observable("OBS_E2F", E2F(b=None))
	Observable("OBS_CycE", CycE(c=None))
	Observable("OBS_CycA", CycA(c=None))
	Observable("OBS_Int", I())
	Observable("OBS_Mdm2", Mdm2(i=None))
	Observable("OBS_p21", p21(b=None))
	Observable("OBS_p16", p16(b=None))
	Observable("OBS_Rb", Rb(b=None, Y='u'))
	Observable("OBS_CycD_CDK46", CycD(c=1) % CDK46(Y='p',b=None,c=1))
	Observable("signal", Signal())
	Observable("signal_damp", SignalDamp())

###############
## Functions ##
## Implemented by Corey Hayford ##

def declare_functions():
	Expression("create_p16", sympify("k41/((One + k42*OBS_Rb) - (k43*OBS_p16 + k44*OBS_p16*OBS_CycD_CDK46))"))
	Expression("create_Rb", sympify("k58/(One + k59*OBS_p16)"))
	Expression("create_Mdm2", sympify("k66*OBS_Int**9/(k65**9 + OBS_Int**9)"))
	Expression("create_Int", sympify("(k70*OBS_p53*signal)/(One + k71*OBS_p53*OBS_Mdm2)"))
	Expression("sig_deg", sympify("k74 - k73*(signal-signal_damp)"))
	Expression("kdamp_DDS0", sympify("k75*DDS_0"))

###########
## Rules ##
###########

def simulate_signal_degradation():
# 	##### DNA Damage Signal ####
	Rule('Signal_Degrade', Signal() >> None, k72)
	Rule('Signal_Damp', SignalDamp() >> None, kdamp_DDS0)
	


# Figure 1 in Iwamoto et al. 
# Reactions 1-14
def p16_p27_inhibition():
	# Synthesis and Degradation
	synthesize_degrade_table([[CycD(c=None),	k1,		k2],	#1,2
							  [p27(b=None),		k34,	None],	#10
							  [p16(b=None),		k40,	None]])	#11,13
	# Inhibition by p27
	bind_table_complex([[										p27(b=None)	],
						[CycD(c=1) % CDK46(Y='p',b=None,c=1),	(k20, k21)	],	#5
						[CycE(c=1) % CDK2( Y='p',b=None,c=1),	(k24, k25)	],	#7
						[CycA(c=1) % CDK2( Y='p',b=None,c=1),	(k30, k31)	]],	#9
						'b', 'b')
						
	#TODO: Clean up below
	equilibrate(CycD(c=None) + CDK46(Y='u',b=None,c=None), CycD(c=1) % CDK46(Y='p',b=None,c=1), [k3, k4])			#3	Activation of CDK4/6 by CycD
	Rule("R4", CycD(c=1) % CDK46(Y='p',b=None,c=1) >> CDK46(Y='u',b=None,c=None), k13)	#4	Degradation of bound CycD
	
	Rule("Degrade_p16_from_CycD_CDK46", p16(b=None) + CycD(c=1) % CDK46(Y='p',b=None,c=1) >>  p16(b=None), k44)   		#14 Degradation of p16/CycD/CDK4/6 complex
	catalyze_one_step(CycE(c=1) % CDK2(Y='p',b=None,c=1), p27(b=None), None, k35)		#6	Degradation of p27 by CycE/CDK2 complex
# 	catalyze_one_step(CycA(c=1) % CDK2(Y='p',b=None,c=1), p27(b=None), None, k36)		#8	Degradation of p27 by CycA/CDK2 complex
	Rule("Degrade_p27_from_CycA_CDK2P", p27(b=None) + CycA(c=1) % CDK2(Y='p',b=None,c=1) >> CycA(c=1) % CDK2(Y='p',b=None,c=1), k36)
# 	catalyze_one_step(Rb(b=None,Y='u'), p16(b=None), None, k41)							#12 Inhibition of p16 by pRb
	Rule("Create_p16", None >> p16(b=None), create_p16)
	

# Figure 2 in Iwamoto et al.
# Reactions 15-30
def CDK2_activation():
	# Synthesis and Degradation
	synthesize_degrade_table([[CycE(c=None),	None,	k6],	#16
							  [CycA(c=None),	None,	k10],	#19
							  [X(), 			None,	k69]])	#30
	# Activation of CDK2
	bind_table_complex([[				CDK2(Y='u',b=None,c=None)	],	
						[CycE(c=None),	(k7, 	k8)					],	#17
						[CycA(c=None),	(k11, 	k12)				]],	#20
						'c','c')
	#TODO: Clean up below
	catalyze_one_step(E2F(b=None), None, X(), 			k68)	#29 Activation of "X" synthesis by E2F
	catalyze_one_step(E2F(b=None), None, CycE(c=None), 	k5)		#15 Activation of CycE synthesis by E2F
	catalyze_one_step(X(), 		   None, CycA(c=None), 	k9)		#18 Activation of CycA synthesis by "X"
	Rule("R21", CycA(c=1) % CDK2(Y='p',b=None,c=1) >> CDK2(Y='u',b=None,c=None), k14)			#21	Degradation of bound CycA
	Rule("R22", CycA(c=1) % CDK2(Y='u',b=None,c=1) >> CDK2(Y='u',b=None,c=None), k15)			#22	Degradation of bound CycA
	Rule("R23", CycE(c=1) % CDK2(Y='u',b=None,c=1) >> CDK2(Y='u',b=None,c=None), k16)			#23	Degradation of bound CycE
	Rule("R26", CycE(c=1) % CDK2(Y='p',b=None,c=1) >> CycE(c=1) % CDK2(Y='u',b=None,c=1), k23)	#26	Dephosphorylation of CycE/CDK2 complex
	Rule("R28", CycA(c=1) % CDK2(Y='p',b=None,c=1) >> CycA(c=1) % CDK2(Y='u',b=None,c=1), k29)	#28	Dephosphorylation of CycA/CDK2 complex
	catalyze_one_step(CycE(c=1) % CDK2(Y='p',b=None,c=1), CycE(c=1) % CDK2(Y='p',b=None,c=1), CDK2(Y='u',b=None,c=None), k17)			#24 Self-inactivation of CycE/CDK2
	catalyze_one_step(CycE(c=1) % CDK2(Y='p',b=None,c=1), CycE(c=1) % CDK2(Y='u',b=None,c=1), CycE(c=1) % CDK2(Y='p',b=None,c=1), k22)	#25 Self-phosphorylation of CycE/CDK2
	catalyze_one_step(CycA(c=1) % CDK2(Y='p',b=None,c=1), CycA(c=1) % CDK2(Y='u',b=None,c=1), CycA(c=1) % CDK2(Y='p',b=None,c=1), k28)	#27 Self-phosphorylation of CycA/CDK2
	
	alias_model_components()

# Figure 3 in Iwamoto et al.
# Reactions 31-44
def Rb_E2F_activation():
	# Synthesis and Degradation
	synthesize_degrade_table([[E2F(b=None),			k52, k53],	#38,39
							  [Rb(Y='u',b=None),	k56, k57]])	#42,43

	#32	Phosphorylation of Rb/E2F complex by CycD/CDK4/6 complex	TODO: change to "catalyze_state"
	catalyze_one_step(CycD(c=1) % CDK46(Y='p',b=None,c=1), Rb(Y='u',b=2) % E2F(b=2), Rb(Y='pp',b=2) % E2F(b=2), k46)
	#33 Phosphorylation of Rb/E2F complex by p27/CycD/CDK4/6 complex	TODO: change to "catalyze_state"
	catalyze_one_step(CycD(c=1) % CDK46(Y='p',b=2,c=1) % p27(b=2), Rb(Y='u',b=2) % E2F(b=2), Rb(Y='pp',b=2) % E2F(b=2), k47)
	#34 Phosphorylation of Rb/E2F complex by p21/CycD/CDK4/6 complex	TODO: change to "catalyze_state"
	catalyze_one_step(CycD(c=1) % CDK46(Y='p',b=2,c=1) % p21(b=2), Rb(Y='u',b=2) % E2F(b=2), Rb(Y='pp',b=2) % E2F(b=2), k48)
	#35 Cleavage of Rb/E2F complex by CycE/CDK2 complex
	#catalyze_one_step(CycE(c=1) % CDK2(Y='p',b=None,c=1), Rb(Y='pp',b=2) % E2F(b=2), Rb(Y='pppp',b=None) + E2F(b=None), k49)
	Rule("R35", CycE(c=1) % CDK2(Y='p',b=None,c=1) + Rb(Y='pp',b=2) % E2F(b=2) >> Rb(Y='pppp',b=None) + E2F(b=None) + CycE(c=1) % CDK2(Y='p',b=None,c=1), k49)	#35
	#36 Cleavage of Rb/E2F complex by CycA/CDK2 complex
	#catalyze_one_step(CycA(c=1) % CDK2(Y='p',b=None,c=1), Rb(Y='pp',b=2) % E2F(b=2), Rb(Y='pppp',b=None) + E2F(b=None), k50)
	Rule("R36", CycA(c=1) % CDK2(Y='p',b=None,c=1) + Rb(Y='pp',b=2) % E2F(b=2) >> Rb(Y='pppp',b=None) + E2F(b=None) + CycA(c=1) % CDK2(Y='p',b=None,c=1), k50)	#36
	#37 Self-activation of E2F
	catalyze_one_step(E2F(b=None), None, E2F(b=None), k51)
	#40 Degradation of E2F by CycA/CDK2 complex
	catalyze_one_step(CycA(c=1) % CDK2(Y='p',b=None,c=1), E2F(b=None), None, k54)
	#44 Inhibition of Rb by p16
# 	catalyze_one_step(p16(b=None), Rb(Y='u',b=None), None, k58)
	Rule("R31", E2F(b=None) + Rb(b=None,Y='u') >> E2F(b=2) % Rb(b=2,Y='u'), k45)	#31
	Rule("R41", Rb(b=None, Y='pppp') >> Rb(b=None,Y='u'), k55)	#41
	Rule("Create_Rb", None >> Rb(b=None, Y='u'), create_Rb)
	
	

# Figure 4 in Iwamoto et al.
# Reactions 45-58
def DNA_damage_pathway():
	# Synthesis and Degradation
	synthesize_degrade_table([[p21(b=None),		k37, k39],		#48,50
							  [p53(b=None),		k60, k62],		#51,53
							  [Mdm2(i=None),	k63, k64],		#54,55
							  [I(),				None, k67]])	#58,57
							  
	# Inhibition by p21
	bind_table_complex([[										p21(b=None)	],
						[CycD(c=1) % CDK46(Y='p',b=None,c=1),	(k18, k19)	],	#45
						[CycE(c=1) % CDK2( Y='p',b=None,c=1),	(k26, k27)	],	#46
						[CycA(c=1) % CDK2( Y='p',b=None,c=1),	(k32, k33)	]],	#47
						'b','b')

	#49 Activation of p21 synthesis by p53
	catalyze_one_step(p53(b=None), None, p21(b=None), k38)
	#52 Activation of p53 synthesis by DNA Damage Signal
	catalyze_one_step(Signal(), None, p53(b=None), k61)
	#56 Activation of Mdm2 synthesis by "I"
# 	catalyze_one_step(I(), None, Mdm2(i=None), k66)
	#59 Degradation of p53 by Mdm2
# 	catalyze_one_step(Mdm2(i=None), p53(b=None), None, k74)
	Rule("Create_Mdm2", None >> Mdm2(i=None), create_Mdm2)
	Rule("Create_Int", None >> I(), create_Int)
	Rule('p53_Create_Mdm2', p53() + Mdm2() >> Mdm2(), sig_deg)

	# Credit: Michael
	# Non-competitive inhibition of Signal by Mdm2
	# Catalysis of p53 to I by Signal
# 	Rule("R58_1", p53(b=None) + Signal(b=None,i=None) <> p53(b=1) % Signal(b=1,i=None), k57, k59)
# 	Rule("R58_2", p53(b=1) % Signal(b=1,i=None) + Mdm2(i=None) <> p53(b=1) % Signal(b=1,i=2) % Mdm2(i=2), k57, k58)
# 	Rule("R58_3", p53(b=1) % Signal(b=1,i=None) >> I() + Signal(b=None,i=None), k57)
	
	
	
	
	
	
	

# def low_damage():
# 	set_dna_damage(0)
# 	dna_damage_monomers()
# 	declare_initial_conditions()
# 	declare_kinetic_parameters()
# 	simulate_signal_degradation()
# 	p16_p27_inhibition()
# 	CDK2_activation()
# 	Rb_E2F_activation()
# 	DNA_damage_pathway()
# 
# def high_damage():
# 	set_dna_damage(0.005)
# 	dna_damage_monomers()
# 	declare_initial_conditions()
# 	declare_kinetic_parameters()
# 	simulate_signal_degradation()
# 	p16_p27_inhibition()
# 	CDK2_activation()
# 	Rb_E2F_activation()
# 	DNA_damage_pathway()
# 	
# # run
# 
# high_damage()


